Update Deployment_Actions.yaml

diff --git a/.github/workflows/Deployment_Actions.yaml b/.github/workflows/Deployment_Actions.yaml
--- a/.github/workflows/Deployment_Actions.yaml
+++ b/.github/workflows/Deployment_Actions.yaml
@@ -46,6 +46,18 @@ jobs:
           cd Docker
           docker-compose -f "docker-compose.yml" up -d --build
 
+      - name: "Integration Test1-Check access WebPage index.html from Docker Compose"
+        run: |
+              STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "http://localhost:80/index.html")
+              if [[ "${STATUS}" -eq 200 ]]; then
+                echo "Status connection OK!!!"
+                exit 0
+              else
+                echo "Error access"
+                echo "Status connection ERROR!!!: $STATUS"
+                exit 1
+              fi
+
       - name: Stop containers
         if: always()
         run: |
